import {
  API_ENDPOINTS,
  CAPABILITIES,
  CODE_SAMPLES,
  FACTS,
  FAQ,
  PIPELINE,
  PROVIDER_NAMES,
  QUICKSTART,
  SITE,
  SITE_URL,
  faqAnswerText,
} from '@/lib/site-content';

export const dynamic = 'force-static';

/**
 * `/llms-full.txt` — the flat, expanded variant of `/llms.txt`.
 *
 * Same structure, but with every code sample, parameter table and pipeline stage
 * inlined so a model can consume the whole documentation set in one fetch
 * without following links.
 */
export function GET() {
  const sections: string[] = [];

  sections.push(`# ${SITE.name} — complete documentation

> ${SITE.definition}

Source: ${SITE.repoUrl}
Version: v${SITE.version} (no tagged releases yet)
License: ${SITE.license} — the full text is in the LICENSE file at the repository
root. Bundled third-party packages keep their own licenses (MIT, ISC,
Apache-2.0); the README lists them.
Documentation site: ${SITE_URL}${SITE.docsPath}
Interactive studio: ${SITE_URL}${SITE.entryPath}
Stack: Next.js 15 App Router (standalone output), React 19.2, TypeScript 5.9,
Tailwind CSS 4.1, @google/genai 2.x, motion 12, canvas-confetti 1.9, react-markdown 10.
Runtime: Node.js 20+. Runtime secret: GEMINI_API_KEY (optional, server-side only).`);

  sections.push(`## Contents

${FACTS.map((fact) => `- ${fact.value} ${fact.label.toLowerCase()} — \`${fact.detail}\``).join('\n')}`);

  sections.push(`## Architecture: the keystroke pipeline

Ordered exactly as the code executes it.

${PIPELINE.map(
  (stage, index) => `### ${index + 1}. ${stage.title}

- File: \`${stage.actor}\`
- Behaviour: ${stage.detail}`
).join('\n\n')}

### Design constraints

1. Keystroke intervals use \`performance.now()\` (monotonic). \`Date.now()\` can jump
   on NTP correction and would corrupt inter-key latency, consistency scores and
   the adaptive difficulty baselines.
2. Typing logic never lives in a React component. \`TypingEngine\` owns character
   state, timing and grading; components own presentation only.
3. The localStorage progress schema is treated as immutable. Storage keys keep
   their legacy \`typepulse_\` prefix because renaming them would silently discard
   existing user progress.`);

  sections.push(`## Capabilities

${CAPABILITIES.map(
  (capability) =>
    `### ${capability.title}\n\n${capability.summary}\n\n${capability.bullets
      .map((bullet) => `- ${bullet}`)
      .join('\n')}`
).join('\n\n')}`);

  sections.push(`## Code samples

${CODE_SAMPLES.map(
  (sample) =>
    `### ${sample.label}\n\n\`\`\`${sample.language}\n${sample.code}\n\`\`\``
).join('\n\n')}`);

  sections.push(`## HTTP API

${API_ENDPOINTS.map(
  (endpoint) =>
    `### ${endpoint.method} ${endpoint.path}\n\n${endpoint.description}\n\n| Parameter | Type | Requirement | Description |\n| --- | --- | --- | --- |\n${endpoint.params
      .map(
        (param) =>
          `| \`${param.name}\` | \`${param.type}\` | ${param.required} | ${param.description} |`
      )
      .join('\n')}\n\nResponse:\n\n\`\`\`json\n${endpoint.response}\n\`\`\`\n\nNotes:\n${endpoint.notes
      .map((note) => `- ${note}`)
      .join('\n')}`
).join('\n\n')}`);

  sections.push(`## Self-hosting

${QUICKSTART.map(
  (step) =>
    `### ${step.step} — ${step.title}\n\n\`\`\`bash\n${step.code}\n\`\`\``
).join('\n\n')}

### Coach providers

${PROVIDER_NAMES.map((provider) => `- ${provider}`).join('\n')}

Provider selection is a user setting (\`typepulse_ai_settings\` in localStorage),
not a build-time decision. The local presets (Ollama, LM Studio) keep every
request on the user's own machine.`);

  sections.push(`## Frequently asked questions

${FAQ.map((entry) => `### ${entry.question}\n\n${faqAnswerText(entry)}`).join('\n\n')}`);

  sections.push(`## Storage schema

All progress is local. Keys and responsibilities:

- \`typepulse_user_progress\` — XP, level, achievements, key statistics, high scores, arcade scores
- \`typepulse_preferences\` — theme, sound profile, error mode, accessibility toggles
- \`typepulse_ai_settings\` — provider, endpoint, model, temperature, proxy flag
- \`typepulse_arcade_stats\` — per-title arcade records
- \`typepulse_biometric_report\` — latency report generated by the analytics view
- \`typepulse_daily_challenge_record\` — daily challenge completion record
- \`typepulse_duel_career\` — duel win/loss career record

Portable formats: \`exportBackupPackage()\` (JSON), \`exportSyncToken()\` (one-line
token), \`importBackupPackage(raw)\` (accepts either, validates a checksum), and
\`exportGhostPayload(author)\` (URL-safe keystroke timeline usable as
\`${SITE.entryPath}?duel=<payload>\`).`);

  const body = `${sections.join('\n\n---\n\n')}\n`;

  return new Response(body, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=0, s-maxage=3600, stale-while-revalidate=86400',
    },
  });
}
