'use client';

import React, { useState } from 'react';
import { AIMission, AISettings, UserProgress } from '@/types/typing';
import { generateAiMission } from '@/lib/ai-service';
import { Bot, ChevronRight, Flame, Loader2, Plus, Sparkles, Target, Zap } from 'lucide-react';

interface AIMissionBoardProps {
  userProgress: UserProgress;
  aiSettings: AISettings;
  onLaunchMission: (mission: AIMission) => void;
  onBackToPractice: () => void;
  onOpenSettings: () => void;
}

export const AIMissionBoard: React.FC<AIMissionBoardProps> = ({
  userProgress,
  aiSettings,
  onLaunchMission,
  onBackToPractice,
  onOpenSettings,
}) => {
  const [missions, setMissions] = useState<AIMission[]>(() => [
    {
      id: 'default-mission-1',
      type: 'WEAK_KEY_DRILL',
      title: 'Home Row Anchor Recalibration',
      description: 'Stabilize finger transitions across the fundamental home row.',
      difficulty: 'Beginner',
      targetWpm: 24,
      targetAccuracy: 96,
      focusKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l'],
      content: 'all ask fall alas salad flasks fall fads dad add sass dads glad half flag dash',
      rewardXp: 180,
      reason: 'Home row consistency is the foundation of all high-velocity typing.',
      completed: false,
      createdAt: 1700000000000,
    },
    {
      id: 'default-mission-2',
      type: 'ACCURACY_TARGET',
      title: 'Precision Lock Sprint',
      description: 'Finish a steady 30-word flow with zero room for error. Target 97%+ accuracy.',
      difficulty: 'Intermediate',
      targetWpm: 30,
      targetAccuracy: 97,
      content: 'Precision is the foundation of speed. Move smooth, keep calm, and speed will follow naturally without hesitation.',
      rewardXp: 220,
      reason: 'Reinforces the metronome rhythm to eliminate backspace penalties.',
      completed: false,
      createdAt: 1700000000000,
    },
    {
      id: 'default-mission-3',
      type: 'SPEED_SPRINT',
      title: 'Velocity Barrier Breakthrough',
      description: 'Push your boundaries and beat your personal pacing on common words.',
      difficulty: 'Advanced',
      targetWpm: 40,
      targetAccuracy: 94,
      content: 'quick reach rhythm drive build spark track glide shift sound smart steady fluid force craft habit sharp alert motion',
      rewardXp: 280,
      reason: 'High-frequency words are best practiced as reflexive whole-word chords.',
      completed: false,
      createdAt: 1700000000000,
    },
  ]);

  const [generating, setGenerating] = useState(false);

  // Extract weak keys from user progress
  const topWeakKeys = Object.entries(userProgress.keyStats)
    .filter(([char]) => char !== ' ')
    .sort(([, a], [, b]) => b.errors - a.errors)
    .slice(0, 4)
    .map(([char]) => char);

  const handleGenerateNewMission = async () => {
    setGenerating(true);
    try {
      const currentWpm = userProgress.highScores.bestWpm || 30;
      const newMission = await generateAiMission(topWeakKeys, currentWpm, aiSettings);
      setMissions((prev) => [newMission, ...prev]);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-8 animate-fadeIn" id="ai-mission-board-container">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 bg-surface border border-border rounded-2xl shadow-card">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-primary text-xs font-semibold uppercase tracking-wider">
            <Bot className="w-4 h-4" />
            <span>Personalized Training Operations</span>
          </div>
          <h2 className="text-2xl font-bold text-text-primary">AI Mission Board</h2>
          <p className="text-xs text-text-muted max-w-xl">
            Dynamic tactical missions generated by your AI Coach to eradicate finger hesitation, conquer speed plateaus, and enforce metronome accuracy.
          </p>
        </div>

        <div className="flex items-center gap-2 self-start sm:self-center">
          <button
            onClick={handleGenerateNewMission}
            disabled={generating}
            className="px-4 py-2 bg-primary hover:bg-primary/90 disabled:opacity-50 text-primary-foreground text-xs font-semibold rounded-xl flex items-center gap-1.5 transition-colors shadow-glow-accent-sm"
            id="generate-new-mission-button"
          >
            {generating ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                <span>Synthesizing...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-3.5 h-3.5" />
                <span>Generate Custom Mission</span>
              </>
            )}
          </button>
          <button
            onClick={onBackToPractice}
            className="px-3.5 py-2 bg-surface-muted hover:bg-surface-hover text-text-secondary hover:text-text-primary text-xs font-medium rounded-xl border border-border transition-colors"
          >
            Back
          </button>
        </div>
      </div>

      {/* Provider Info Pill */}
      <div className="px-4 py-2.5 bg-surface-muted border border-border rounded-xl flex items-center justify-between text-xs text-text-muted">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-success" />
          <span>Active Intelligence Provider:</span>
          <span className="font-mono text-text-primary font-semibold">
            {aiSettings.provider === 'gemini' ? 'Google Gemini' : aiSettings.model || 'OpenAI Compatible'}
          </span>
        </div>
        <button
          onClick={onOpenSettings}
          className="text-accent hover:underline font-medium underline-offset-2"
        >
          Change AI Endpoint & Model
        </button>
      </div>

      {/* Missions Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {missions.map((mission) => (
          <div
            key={mission.id}
            className="p-5 bg-surface border border-border rounded-2xl flex flex-col justify-between gap-4 hover:border-border-hover transition-all shadow-card"
          >
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span
                  className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full border ${
                    mission.difficulty === 'Master'
                      ? 'bg-danger-subtle border-danger-border text-danger'
                      : mission.difficulty === 'Advanced'
                      ? 'bg-accent-subtle border-accent-border text-accent'
                      : 'bg-primary-subtle border-primary-border text-primary'
                  }`}
                >
                  {mission.difficulty} • {mission.type.replace(/_/g, ' ')}
                </span>
                <span className="text-xs font-mono font-bold text-accent">+{mission.rewardXp} XP</span>
              </div>

              <h3 className="font-bold text-text-primary text-base">{mission.title}</h3>
              <p className="text-xs text-text-muted">{mission.description}</p>

              {/* Coach Insight */}
              <div className="p-2.5 bg-surface-muted border border-border rounded-xl text-[11px] text-text-secondary flex items-start gap-2">
                <Bot className="w-3.5 h-3.5 text-primary shrink-0 mt-0.5" />
                <p>{mission.reason}</p>
              </div>
            </div>

            {/* Target Criteria & Action */}
            <div className="pt-3 border-t border-border flex items-center justify-between text-xs text-text-muted">
              <div className="flex items-center gap-3 font-mono">
                {mission.targetWpm && (
                  <span className="flex items-center gap-1 text-accent">
                    <Zap className="w-3 h-3" />
                    {mission.targetWpm} WPM
                  </span>
                )}
                {mission.targetAccuracy && (
                  <span className="flex items-center gap-1 text-success">
                    <Target className="w-3 h-3" />
                    {mission.targetAccuracy}% Acc
                  </span>
                )}
              </div>

              <button
                type="button"
                onClick={() => onLaunchMission(mission)}
                className="px-4 py-1.5 bg-accent hover:bg-accent-hover text-accent-foreground font-bold text-xs rounded-xl flex items-center gap-1.5 transition-colors shadow-glow-accent-sm"
                id={`launch-mission-${mission.id}`}
              >
                <span>Deploy</span>
                <ChevronRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
