'use client';

import React, { useState } from 'react';
import { AIMission, AISettings, UserProgress } from '@/types/typing';
import { generateAiMission } from '@/lib/ai-service';
import { Bot, ChevronRight, Flame, Loader2, Plus, Sparkles, Target, Zap } from 'lucide-react';

interface AIMissionBoardProps {
  userProgress: UserProgress;
  aiSettings: AISettings;
  onLaunchMission: (mission: AIMission) => void;
  onBackToPractice: () => void;
  onOpenSettings: () => void;
}

export const AIMissionBoard: React.FC<AIMissionBoardProps> = ({
  userProgress,
  aiSettings,
  onLaunchMission,
  onBackToPractice,
  onOpenSettings,
}) => {
  const [missions, setMissions] = useState<AIMission[]>(() => [
    {
      id: 'default-mission-1',
      type: 'WEAK_KEY_DRILL',
      title: 'Home Row Anchor Recalibration',
      description: 'Stabilize finger transitions across the fundamental home row.',
      difficulty: 'Beginner',
      targetWpm: 24,
      targetAccuracy: 96,
      focusKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l'],
      content: 'all ask fall alas salad flasks fall fads dad add sass dads glad half flag dash',
      rewardXp: 180,
      reason: 'Home row consistency is the foundation of all high-velocity typing.',
      completed: false,
      createdAt: 1700000000000,
    },
    {
      id: 'default-mission-2',
      type: 'ACCURACY_TARGET',
      title: 'Precision Lock Sprint',
      description: 'Finish a steady 30-word flow with zero room for error. Target 97%+ accuracy.',
      difficulty: 'Intermediate',
      targetWpm: 30,
      targetAccuracy: 97,
      content: 'Precision is the foundation of speed. Move smooth, keep calm, and speed will follow naturally without hesitation.',
      rewardXp: 220,
      reason: 'Reinforces the metronome rhythm to eliminate backspace penalties.',
      completed: false,
      createdAt: 1700000000000,
    },
    {
      id: 'default-mission-3',
      type: 'SPEED_SPRINT',
      title: 'Velocity Barrier Breakthrough',
      description: 'Push your boundaries and beat your personal pacing on common words.',
      difficulty: 'Advanced',
      targetWpm: 40,
      targetAccuracy: 94,
      content: 'quick reach rhythm drive build spark track glide shift sound smart steady fluid force craft habit sharp alert motion',
      rewardXp: 280,
      reason: 'High-frequency words are best practiced as reflexive whole-word chords.',
      completed: false,
      createdAt: 1700000000000,
    },
  ]);

  const [generating, setGenerating] = useState(false);

  // Extract weak keys from user progress
  const topWeakKeys = Object.entries(userProgress.keyStats)
    .filter(([char]) => char !== ' ')
    .sort(([, a], [, b]) => b.errors - a.errors)
    .slice(0, 4)
    .map(([char]) => char);

  const handleGenerateNewMission = async () => {
    setGenerating(true);
    try {
      const currentWpm = userProgress.highScores.bestWpm || 30;
      const newMission = await generateAiMission(topWeakKeys, currentWpm, aiSettings);
      setMissions((prev) => [newMission, ...prev]);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-8 animate-fadeIn" id="ai-mission-board-container">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 bg-slate-900/90 border border-slate-800 rounded-2xl shadow-xl">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-indigo-400 text-xs font-semibold uppercase tracking-wider">
            <Bot className="w-4 h-4" />
            <span>Personalized Training Operations</span>
          </div>
          <h2 className="text-2xl font-bold text-slate-100">AI Mission Board</h2>
          <p className="text-xs text-slate-400 max-w-xl">
            Dynamic tactical missions generated by your AI Coach to eradicate finger hesitation, conquer speed plateaus, and enforce metronome accuracy.
          </p>
        </div>

        <div className="flex items-center gap-2 self-start sm:self-center">
          <button
            onClick={handleGenerateNewMission}
            disabled={generating}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white text-xs font-semibold rounded-xl flex items-center gap-1.5 transition-colors shadow-lg shadow-indigo-600/20"
            id="generate-new-mission-button"
          >
            {generating ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                <span>Synthesizing...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-3.5 h-3.5" />
                <span>Generate Custom Mission</span>
              </>
            )}
          </button>
          <button
            onClick={onBackToPractice}
            className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-xl border border-slate-700 transition-colors"
          >
            Back
          </button>
        </div>
      </div>

      {/* Provider Info Pill */}
      <div className="px-4 py-2.5 bg-slate-900/60 border border-slate-800 rounded-xl flex items-center justify-between text-xs text-slate-400">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-emerald-400" />
          <span>Active Intelligence Provider:</span>
          <span className="font-mono text-slate-200 font-semibold">
            {aiSettings.provider === 'gemini' ? 'Google Gemini' : aiSettings.model || 'OpenAI Compatible'}
          </span>
        </div>
        <button
          onClick={onOpenSettings}
          className="text-amber-400 hover:text-amber-300 font-medium underline-offset-2 hover:underline"
        >
          Change AI Endpoint & Model
        </button>
      </div>

      {/* Missions Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {missions.map((mission) => (
          <div
            key={mission.id}
            className="p-5 bg-slate-900/70 border border-slate-800 rounded-2xl flex flex-col justify-between gap-4 hover:border-slate-700 transition-all shadow-md"
          >
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span
                  className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full border ${
                    mission.difficulty === 'Master'
                      ? 'bg-rose-500/15 border-rose-500/40 text-rose-300'
                      : mission.difficulty === 'Advanced'
                      ? 'bg-amber-500/15 border-amber-500/40 text-amber-300'
                      : 'bg-indigo-500/15 border-indigo-500/40 text-indigo-300'
                  }`}
                >
                  {mission.difficulty} • {mission.type.replace(/_/g, ' ')}
                </span>
                <span className="text-xs font-mono font-bold text-amber-400">+{mission.rewardXp} XP</span>
              </div>

              <h3 className="font-bold text-slate-100 text-base">{mission.title}</h3>
              <p className="text-xs text-slate-400">{mission.description}</p>

              {/* Coach Insight */}
              <div className="p-2.5 bg-slate-950/70 border border-indigo-500/20 rounded-xl text-[11px] text-indigo-200 flex items-start gap-2">
                <Bot className="w-3.5 h-3.5 text-indigo-400 shrink-0 mt-0.5" />
                <p>{mission.reason}</p>
              </div>
            </div>

            {/* Target Criteria & Action */}
            <div className="pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs text-slate-400">
              <div className="flex items-center gap-3 font-mono">
                {mission.targetWpm && (
                  <span className="flex items-center gap-1 text-amber-400">
                    <Zap className="w-3 h-3" />
                    {mission.targetWpm} WPM
                  </span>
                )}
                {mission.targetAccuracy && (
                  <span className="flex items-center gap-1 text-emerald-400">
                    <Target className="w-3 h-3" />
                    {mission.targetAccuracy}% Acc
                  </span>
                )}
              </div>

              <button
                type="button"
                onClick={() => onLaunchMission(mission)}
                className="px-4 py-1.5 bg-amber-400 hover:bg-amber-300 text-slate-950 font-bold text-xs rounded-xl flex items-center gap-1.5 transition-colors shadow-sm"
                id={`launch-mission-${mission.id}`}
              >
                <span>Deploy</span>
                <ChevronRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
