import { Achievement } from '@/types/typing';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  // Core Onboarding
  {
    id: 'first_keystroke',
    name: 'First Spark',
    description: 'Complete your very first typing session.',
    icon: 'Sparkles',
    category: 'games',
    progress: 0,
    maxProgress: 1,
    xpReward: 50,
  },

  // Velocity Milestones (Speed)
  {
    id: 'speed_30',
    name: 'Swift Hands',
    description: 'Reach 30 WPM in any typing session.',
    icon: 'Zap',
    category: 'speed',
    progress: 0,
    maxProgress: 30,
    xpReward: 100,
  },
  {
    id: 'speed_60',
    name: 'Speed Demon',
    description: 'Break the 60 WPM benchmark with steady rhythm.',
    icon: 'Flame',
    category: 'speed',
    progress: 0,
    maxProgress: 60,
    xpReward: 250,
  },
  {
    id: 'speed_90',
    name: 'Sound Barrier',
    description: 'Surpass 90 WPM with high-octane touch typing velocity.',
    icon: 'Rocket',
    category: 'speed',
    progress: 0,
    maxProgress: 90,
    xpReward: 600,
  },
  {
    id: 'speed_100',
    name: 'Velocity Centurion',
    description: 'Break triple digits with 100 WPM or higher.',
    icon: 'Zap',
    category: 'speed',
    progress: 0,
    maxProgress: 100,
    xpReward: 1000,
  },
  {
    id: 'speed_120',
    name: 'Supersonic Typist',
    description: 'Reach world-class 120 WPM keyboard velocity.',
    icon: 'Rocket',
    category: 'speed',
    progress: 0,
    maxProgress: 120,
    xpReward: 1800,
  },

  // Accuracy & Precision
  {
    id: 'accuracy_95',
    name: 'Sharpshooter',
    description: 'Finish a session with 95% accuracy or higher (min 60 keystrokes).',
    icon: 'Target',
    category: 'accuracy',
    progress: 0,
    maxProgress: 1,
    xpReward: 100,
  },
  {
    id: 'accuracy_98',
    name: 'Laser Precision',
    description: 'Finish a session with 98% accuracy or higher (min 80 keystrokes).',
    icon: 'Crosshair',
    category: 'accuracy',
    progress: 0,
    maxProgress: 1,
    xpReward: 200,
  },
  {
    id: 'accuracy_100',
    name: 'Flawless Flow',
    description: 'Finish a test with 100% perfection and zero mistakes.',
    icon: 'ShieldCheck',
    category: 'accuracy',
    progress: 0,
    maxProgress: 1,
    xpReward: 400,
  },

  // Flawless Combos
  {
    id: 'combo_50',
    name: 'Combo Specialist',
    description: 'Maintain a 50-character streak without a single mistake.',
    icon: 'Activity',
    category: 'combo',
    progress: 0,
    maxProgress: 50,
    xpReward: 150,
  },
  {
    id: 'combo_100',
    name: 'Centurion Combo',
    description: 'Achieve a 100-character flawless uninterrupted streak.',
    icon: 'Award',
    category: 'combo',
    progress: 0,
    maxProgress: 100,
    xpReward: 350,
  },

  // Daily Consistency Streaks
  {
    id: 'streak_3',
    name: 'Dedicated Student',
    description: 'Maintain a 3-day daily typing streak.',
    icon: 'Calendar',
    category: 'streak',
    progress: 0,
    maxProgress: 3,
    xpReward: 200,
  },
  {
    id: 'streak_7',
    name: 'Habit of Excellence',
    description: 'Keep a 7-day daily typing streak alive.',
    icon: 'Trophy',
    category: 'streak',
    progress: 0,
    maxProgress: 7,
    xpReward: 500,
  },
  {
    id: 'streak_14',
    name: 'Unstoppable Momentum',
    description: 'Keep a 14-day daily typing streak alive without missing a day.',
    icon: 'Flame',
    category: 'streak',
    progress: 0,
    maxProgress: 14,
    xpReward: 1000,
  },
  {
    id: 'streak_30',
    name: 'Zen Master of Habit',
    description: 'Forge an unbroken 30-day daily typing habit of true mastery.',
    icon: 'Award',
    category: 'streak',
    progress: 0,
    maxProgress: 30,
    xpReward: 2500,
  },

  // Standards-Aligned 7-Unit Curriculum Milestones
  {
    id: 'lessons_tier1',
    name: 'Home Row Anchor Graduate',
    description: 'Complete all 6 Unit 1 Home Row Foundation lessons.',
    icon: 'BookOpen',
    category: 'lessons',
    progress: 0,
    maxProgress: 6,
    xpReward: 350,
  },
  {
    id: 'unit2_master',
    name: 'Top Deck Navigator',
    description: 'Master all 6 Unit 2 Top Row Reach lessons (vowels & consonants).',
    icon: 'BookOpen',
    category: 'lessons',
    progress: 0,
    maxProgress: 6,
    xpReward: 400,
  },
  {
    id: 'unit3_master',
    name: 'Full Alphabet Virtuoso',
    description: 'Master all 6 Unit 3 Bottom Row Slide lessons across all 26 letters.',
    icon: 'BookOpen',
    category: 'lessons',
    progress: 0,
    maxProgress: 6,
    xpReward: 450,
  },
  {
    id: 'unit4_master',
    name: 'Shift Key Tactician',
    description: 'Conquer Unit 4 opposite-hand Shift capitalization and dialogue.',
    icon: 'BookOpen',
    category: 'lessons',
    progress: 0,
    maxProgress: 6,
    xpReward: 500,
  },
  {
    id: 'unit5_master',
    name: 'Numeric Data Specialist',
    description: 'Master Unit 5 Number Row reaches, dates, times, and tabular metrics.',
    icon: 'BookOpen',
    category: 'lessons',
    progress: 0,
    maxProgress: 6,
    xpReward: 550,
  },
  {
    id: 'unit6_master',
    name: 'Syntax & Code Architect',
    description: 'Conquer Unit 6 developer brackets, arrows, and punctuation.',
    icon: 'BookOpen',
    category: 'lessons',
    progress: 0,
    maxProgress: 6,
    xpReward: 600,
  },
  {
    id: 'curriculum_graduate',
    name: 'International Academy Graduate',
    description: 'Complete all 42 lessons across all 7 certified curriculum units.',
    icon: 'Trophy',
    category: 'lessons',
    progress: 0,
    maxProgress: 42,
    xpReward: 2000,
  },

  // Standardized International Certification Tiers
  {
    id: 'cert_bronze',
    name: 'Certified Bronze Typist',
    description: 'Achieve ≥30 WPM and ≥95% accuracy on an official timed benchmark.',
    icon: 'Award',
    category: 'speed',
    progress: 0,
    maxProgress: 1,
    xpReward: 300,
  },
  {
    id: 'cert_silver',
    name: 'Certified Silver Scribe',
    description: 'Achieve ≥50 WPM and ≥96% accuracy on an official timed benchmark.',
    icon: 'Award',
    category: 'speed',
    progress: 0,
    maxProgress: 1,
    xpReward: 600,
  },
  {
    id: 'cert_gold',
    name: 'Certified Gold Velocity Master',
    description: 'Achieve ≥70 WPM and ≥97% accuracy on an official timed benchmark.',
    icon: 'Award',
    category: 'speed',
    progress: 0,
    maxProgress: 1,
    xpReward: 1000,
  },
  {
    id: 'cert_platinum',
    name: 'Certified Platinum Elite',
    description: 'Achieve ≥90 WPM and ≥98% accuracy on an official timed benchmark.',
    icon: 'Trophy',
    category: 'speed',
    progress: 0,
    maxProgress: 1,
    xpReward: 1500,
  },
  {
    id: 'cert_diamond',
    name: 'Certified Diamond Sovereign',
    description: 'Achieve ≥110 WPM and ≥99% accuracy on an official timed benchmark.',
    icon: 'Crown',
    category: 'speed',
    progress: 0,
    maxProgress: 1,
    xpReward: 3000,
  },

  // AI-Assisted Training Milestones
  {
    id: 'ai_mission_complete',
    name: 'AI Sensei Initiate',
    description: 'Deploy and conquer an AI-generated personalized mission.',
    icon: 'Bot',
    category: 'games',
    progress: 0,
    maxProgress: 1,
    xpReward: 200,
  },
  {
    id: 'ai_drill_explorer',
    name: 'Pattern Alchemist',
    description: 'Practice a lesson using an AI-generated whitelist pattern drill.',
    icon: 'Sparkles',
    category: 'games',
    progress: 0,
    maxProgress: 1,
    xpReward: 250,
  },
  {
    id: 'ai_polyglot_coder',
    name: 'Polyglot Syntax Hacker',
    description: 'Complete an AI Code-Pulse developer typing challenge.',
    icon: 'Zap',
    category: 'games',
    progress: 0,
    maxProgress: 1,
    xpReward: 300,
  },
];
