import { Achievement } from '@/types/typing';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_keystroke',
    name: 'First Spark',
    description: 'Complete your very first typing session.',
    icon: 'Sparkles',
    category: 'games',
    progress: 0,
    maxProgress: 1,
    xpReward: 50,
  },
  {
    id: 'speed_30',
    name: 'Swift Hands',
    description: 'Reach 30 WPM in any typing mode.',
    icon: 'Zap',
    category: 'speed',
    progress: 0,
    maxProgress: 30,
    xpReward: 100,
  },
  {
    id: 'speed_60',
    name: 'Speed Demon',
    description: 'Break the 60 WPM barrier.',
    icon: 'Flame',
    category: 'speed',
    progress: 0,
    maxProgress: 60,
    xpReward: 250,
  },
  {
    id: 'speed_90',
    name: 'Sound Barrier',
    description: 'Achieve 90 WPM or higher with clean technique.',
    icon: 'Rocket',
    category: 'speed',
    progress: 0,
    maxProgress: 90,
    xpReward: 600,
  },
  {
    id: 'speed_100',
    name: 'Velocity Centurion',
    description: 'Surpass 100 WPM with high-octane touch typing velocity.',
    icon: 'Zap',
    category: 'speed',
    progress: 0,
    maxProgress: 100,
    xpReward: 1000,
  },
  {
    id: 'accuracy_95',
    name: 'Sharpshooter',
    description: 'Finish a session with 95% accuracy or higher (min 20 words).',
    icon: 'Target',
    category: 'accuracy',
    progress: 0,
    maxProgress: 1,
    xpReward: 100,
  },
  {
    id: 'accuracy_98',
    name: 'Laser Precision',
    description: 'Finish a session with 98% accuracy or higher (min 25 words).',
    icon: 'Crosshair',
    category: 'accuracy',
    progress: 0,
    maxProgress: 1,
    xpReward: 150,
  },
  {
    id: 'accuracy_100',
    name: 'Flawless Flow',
    description: 'Finish a test with 100% perfection and zero mistakes.',
    icon: 'ShieldCheck',
    category: 'accuracy',
    progress: 0,
    maxProgress: 1,
    xpReward: 350,
  },
  {
    id: 'combo_50',
    name: 'Combo Specialist',
    description: 'Maintain a 50-character streak without a single mistake.',
    icon: 'Activity',
    category: 'combo',
    progress: 0,
    maxProgress: 50,
    xpReward: 150,
  },
  {
    id: 'combo_100',
    name: 'Centurion',
    description: 'Achieve a 100-character flawless combo.',
    icon: 'Award',
    category: 'combo',
    progress: 0,
    maxProgress: 100,
    xpReward: 350,
  },
  {
    id: 'lessons_tier1',
    name: 'Home Row Master',
    description: 'Complete all Tier 1 home row foundation lessons.',
    icon: 'BookOpen',
    category: 'lessons',
    progress: 0,
    maxProgress: 4,
    xpReward: 300,
  },
  {
    id: 'streak_3',
    name: 'Dedicated Student',
    description: 'Maintain a 3-day typing streak.',
    icon: 'Calendar',
    category: 'streak',
    progress: 0,
    maxProgress: 3,
    xpReward: 200,
  },
  {
    id: 'streak_7',
    name: 'Habit of Excellence',
    description: 'Keep a 7-day daily typing streak alive.',
    icon: 'Trophy',
    category: 'streak',
    progress: 0,
    maxProgress: 7,
    xpReward: 500,
  },
  {
    id: 'streak_14',
    name: 'Unstoppable Momentum',
    description: 'Keep a 14-day daily typing streak alive without missing a day.',
    icon: 'Flame',
    category: 'streak',
    progress: 0,
    maxProgress: 14,
    xpReward: 1000,
  },
  {
    id: 'streak_30',
    name: 'Zen Master of Habit',
    description: 'Forge an unbroken 30-day daily typing habit of true mastery.',
    icon: 'Award',
    category: 'streak',
    progress: 0,
    maxProgress: 30,
    xpReward: 2500,
  },
  {
    id: 'ai_mission_complete',
    name: 'Coached to Greatness',
    description: 'Complete an AI-generated personalized mission.',
    icon: 'Bot',
    category: 'games',
    progress: 0,
    maxProgress: 1,
    xpReward: 200,
  },
  {
    id: 'word_rush_survivor',
    name: 'Rush Hour',
    description: 'Score over 1,500 points in Word Rush arcade mode.',
    icon: 'Timer',
    category: 'games',
    progress: 0,
    maxProgress: 1500,
    xpReward: 250,
  }
];
