import { Lesson } from '@/types/typing';

/**
 * 42-Lesson International Certified Touch-Typing Curriculum
 * Modeled after Typing.com's standards-aligned Scope & Sequence:
 *   Unit 1: Home Row Foundation (F, J, A, S, D, K, L, ;, G, H)
 *   Unit 2: Top Row Reach (E, I, R, U, T, Y, O, P, Q, W)
 *   Unit 3: Bottom Row Slide (V, M, C, N, X, B, Z, , .)
 *   Unit 4: Capitalization & Shift Mastery (Left Shift, Right Shift, Proper Nouns)
 *   Unit 5: Number Row & Inward Stretches (1, 2, 3, 4, 5, 6, 7, 8, 9, 0)
 *   Unit 6: Punctuation & Developer Symbols (!, ?, ', ", -, _, @, #, $, %, &, *, (, ), {, }, [, ], =)
 *   Unit 7: Velocity & Certification Sprints (30, 40, 50, 60, 70+ WPM benchmarks)
 */
export const LESSONS_42: Lesson[] = [
  // =========================================================================
  // UNIT 1: HOME ROW FOUNDATION (Index Anchors -> Full Home Spread -> G/H Stretches)
  // =========================================================================
  {
    id: 'lesson-1-1',
    tier: 1,
    tierTitle: 'Unit 1: Home Row Foundation',
    title: '1.1 Anchor Keys: F & J',
    description: 'Feel the tactile bumps on F (left index) and J (right index). Return here without looking.',
    targetKeys: ['f', 'j', ' '],
    targetAccuracy: 95,
    targetWpm: 15,
    content: 'fff jjj fff jjj fjf jfj ff jj f j fj fjf jff jjj fff fjf',
    unlocked: true,
    completed: false,
    stars: 0,
    xpReward: 100,
  },
  {
    id: 'lesson-1-2',
    tier: 1,
    tierTitle: 'Unit 1: Home Row Foundation',
    title: '1.2 Left Hand Home: D & K',
    description: 'Left middle on D, right middle on K. Form rhythmic two-finger digraphs.',
    targetKeys: ['d', 'k', 'f', 'j', ' '],
    targetAccuracy: 95,
    targetWpm: 17,
    content: 'df jk fd kj dff jkk dkf jfd kdf jfk fkd jdf kfd ddd kkk',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 110,
  },
  {
    id: 'lesson-1-3',
    tier: 1,
    tierTitle: 'Unit 1: Home Row Foundation',
    title: '1.3 Left Ring & Right Ring: S & L',
    description: 'Left ring finger on S, right ring finger on L. Build independent finger dexterity.',
    targetKeys: ['s', 'l', 'd', 'k', 'f', 'j', ' '],
    targetAccuracy: 94,
    targetWpm: 18,
    content: 'sl ls fds jkl sad lad ask fall flask dads lads skf dls',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 120,
  },
  {
    id: 'lesson-1-4',
    tier: 1,
    tierTitle: 'Unit 1: Home Row Foundation',
    title: '1.4 Pinky Anchors: A & Semicolon',
    description: 'Left pinky on A, right pinky on ;. Complete the foundational eight resting anchors.',
    targetKeys: ['a', ';', 's', 'l', 'd', 'k', 'f', 'j', ' '],
    targetAccuracy: 94,
    targetWpm: 20,
    content: 'asdf jkl; fdsa ;lkj all ask alas salad fall flask fad dad',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 130,
  },
  {
    id: 'lesson-1-5',
    tier: 1,
    tierTitle: 'Unit 1: Home Row Foundation',
    title: '1.5 Inward Index Stretches: G & H',
    description: 'Reach left index inward to G, right index to H. Immediately snap back to F and J.',
    targetKeys: ['g', 'h', 'f', 'j', 'd', 'k', 's', 'l', 'a'],
    targetAccuracy: 94,
    targetWpm: 22,
    content: 'fgf jhj glad half flag dash flash glass shag had gas gag gala',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 140,
  },
  {
    id: 'lesson-1-6',
    tier: 1,
    tierTitle: 'Unit 1: Home Row Foundation',
    title: '1.6 Home Row Fluency & Words',
    description: 'Combine all ten home row keys into real English words without looking down.',
    targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';'],
    targetAccuracy: 95,
    targetWpm: 24,
    content: 'a fall shall glad half flask dash salad flag flash glass lads',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 160,
  },

  // =========================================================================
  // UNIT 2: TOP ROW REACH (Vowels & Consonants across the upper deck)
  // =========================================================================
  {
    id: 'lesson-2-1',
    tier: 2,
    tierTitle: 'Unit 2: Top Row Reach',
    title: '2.1 Middle Finger Vowels: E & I',
    description: 'Left middle finger reaches up to E; right middle reaches up to I.',
    targetKeys: ['e', 'i', 'd', 'k'],
    targetAccuracy: 94,
    targetWpm: 22,
    content: 'ded kik ded kik feed seek file hide feel kid life like desk fill',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 170,
  },
  {
    id: 'lesson-2-2',
    tier: 2,
    tierTitle: 'Unit 2: Top Row Reach',
    title: '2.2 Index Upper Reach: R & U',
    description: 'Left index reaches up to R; right index reaches up to U.',
    targetKeys: ['r', 'u', 'f', 'j'],
    targetAccuracy: 94,
    targetWpm: 23,
    content: 'frf juj frf juj fur jar run rush rule surf user true pure rug',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 180,
  },
  {
    id: 'lesson-2-3',
    tier: 2,
    tierTitle: 'Unit 2: Top Row Reach',
    title: '2.3 Inward Upper Stretches: T & Y',
    description: 'Left index up-inward to T; right index up-inward to Y. Keep wrists stationary.',
    targetKeys: ['t', 'y', 'f', 'j', 'g', 'h'],
    targetAccuracy: 94,
    targetWpm: 24,
    content: 'ftf jyj ftf jyj they that yet city duty stay try day year dry',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 190,
  },
  {
    id: 'lesson-2-4',
    tier: 2,
    tierTitle: 'Unit 2: Top Row Reach',
    title: '2.4 Ring Finger Reach: W & O',
    description: 'Left ring reaches up to W; right ring reaches up to O.',
    targetKeys: ['w', 'o', 's', 'l'],
    targetAccuracy: 93,
    targetWpm: 25,
    content: 'sws lol sws lol slow flow wood wool look work word row blow',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 200,
  },
  {
    id: 'lesson-2-5',
    tier: 2,
    tierTitle: 'Unit 2: Top Row Reach',
    title: '2.5 Outer Pinky Reach: Q & P',
    description: 'Left pinky reaches up to Q; right pinky reaches up to P.',
    targetKeys: ['q', 'p', 'a', ';'],
    targetAccuracy: 93,
    targetWpm: 25,
    content: 'aqa p;p aqa p;p quit equip pool step keep drop quick pray wrap',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 210,
  },
  {
    id: 'lesson-2-6',
    tier: 2,
    tierTitle: 'Unit 2: Top Row Reach',
    title: '2.6 Top & Home Row Synthesis',
    description: 'Integrate the entire upper keyboard row with home row words and fluid phrases.',
    targetKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    targetAccuracy: 94,
    targetWpm: 26,
    content: 'the power to write quickly requires steady posture and quiet hands',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 220,
  },

  // =========================================================================
  // UNIT 3: BOTTOM ROW SLIDE (Careful downward slides without lifting wrists)
  // =========================================================================
  {
    id: 'lesson-3-1',
    tier: 3,
    tierTitle: 'Unit 3: Bottom Row Slide',
    title: '3.1 Index Downward: V & M',
    description: 'Left index slides down to V; right index slides down to M.',
    targetKeys: ['v', 'm', 'f', 'j'],
    targetAccuracy: 93,
    targetWpm: 24,
    content: 'fvf jmj fvf jmj move view firm palm form fame farm vim mail',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 230,
  },
  {
    id: 'lesson-3-2',
    tier: 3,
    tierTitle: 'Unit 3: Bottom Row Slide',
    title: '3.2 Middle Downward: C & Comma',
    description: 'Left middle slides down to C; right middle slides down to comma (,).',
    targetKeys: ['c', ',', 'd', 'k'],
    targetAccuracy: 93,
    targetWpm: 25,
    content: 'dcd k,k dcd k,k call, cook, code, click, calm, cool, camp,',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 240,
  },
  {
    id: 'lesson-3-3',
    tier: 3,
    tierTitle: 'Unit 3: Bottom Row Slide',
    title: '3.3 Inward Index Downward: B & N',
    description: 'Left index slides down-inward to B; right index down-inward to N.',
    targetKeys: ['b', 'n', 'f', 'j'],
    targetAccuracy: 93,
    targetWpm: 25,
    content: 'fbf jnj fbf jnj born bank bone band bind noun bean burn name',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 250,
  },
  {
    id: 'lesson-3-4',
    tier: 3,
    tierTitle: 'Unit 3: Bottom Row Slide',
    title: '3.4 Ring Downward: X & Period',
    description: 'Left ring slides down to X; right ring slides down to period (.).',
    targetKeys: ['x', '.', 's', 'l'],
    targetAccuracy: 93,
    targetWpm: 26,
    content: 'sxs l.l sxs l.l next. exam. fix. text. mix. axis. flex. box.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 260,
  },
  {
    id: 'lesson-3-5',
    tier: 3,
    tierTitle: 'Unit 3: Bottom Row Slide',
    title: '3.5 Pinky Downward: Z & Slash',
    description: 'Left pinky slides down to Z; right pinky slides down to slash (/).',
    targetKeys: ['z', '/', 'a', ';'],
    targetAccuracy: 92,
    targetWpm: 25,
    content: 'aza ;/; aza ;/; zero zone zoom zinc maze size lazy buzz prize',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 270,
  },
  {
    id: 'lesson-3-6',
    tier: 3,
    tierTitle: 'Unit 3: Bottom Row Slide',
    title: '3.6 Complete Alphabet Panorama',
    description: 'Traverse all twenty-six letters across three rows in full prose flow.',
    targetKeys: ['all'],
    targetAccuracy: 94,
    targetWpm: 28,
    content: 'pack my box with five dozen liquor jugs and amaze the crowd',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 290,
  },

  // =========================================================================
  // UNIT 4: CAPITALIZATION & SHIFT (Opposite-Hand Shift Rules)
  // =========================================================================
  {
    id: 'lesson-4-1',
    tier: 4,
    tierTitle: 'Unit 4: Capitalization & Shift',
    title: '4.1 Right Shift for Left Hand Letters',
    description: 'Depress right Shift with right pinky; strike left-hand capital letters (A, S, D, F, etc.).',
    targetKeys: ['Shift', 'A', 'S', 'D', 'F', 'E', 'R', 'T'],
    targetAccuracy: 94,
    targetWpm: 26,
    content: 'America Friday Europe Tuesday Dave Sam Fred Texas April Earth',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 300,
  },
  {
    id: 'lesson-4-2',
    tier: 4,
    tierTitle: 'Unit 4: Capitalization & Shift',
    title: '4.2 Left Shift for Right Hand Letters',
    description: 'Depress left Shift with left pinky; strike right-hand capital letters (J, K, L, U, I, O, P).',
    targetKeys: ['Shift', 'J', 'K', 'L', 'U', 'I', 'O', 'P'],
    targetAccuracy: 94,
    targetWpm: 26,
    content: 'Japan London Paris India Tokyo Oslo Korea United July October',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 310,
  },
  {
    id: 'lesson-4-3',
    tier: 4,
    tierTitle: 'Unit 4: Capitalization & Shift',
    title: '4.3 Proper Nouns & Title Case',
    description: 'Fluidly alternate Shift hands without breaking typing cadence.',
    targetKeys: ['Shift'],
    targetAccuracy: 95,
    targetWpm: 28,
    content: 'The Great Gatsby and Pride and Prejudice are Famous Classic Books',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 320,
  },
  {
    id: 'lesson-4-4',
    tier: 4,
    tierTitle: 'Unit 4: Capitalization & Shift',
    title: '4.4 Acronyms & Fast Shift Bursts',
    description: 'Short multi-letter acronym bursts (NASA, HTML, API, CPU, CSS).',
    targetKeys: ['Shift'],
    targetAccuracy: 94,
    targetWpm: 30,
    content: 'NASA built the Apollo CPU while W3C drafted the HTML and CSS standards',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 330,
  },
  {
    id: 'lesson-4-5',
    tier: 4,
    tierTitle: 'Unit 4: Capitalization & Shift',
    title: '4.5 Shift with Common Punctuation',
    description: 'Parentheses, exclamation marks, and question marks paired with capitals.',
    targetKeys: ['Shift', '!', '?', '(', ')'],
    targetAccuracy: 94,
    targetWpm: 30,
    content: 'Wait! Did Alice see London (and Paris) before leaving? Yes! Indeed!',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 340,
  },
  {
    id: 'lesson-4-6',
    tier: 4,
    tierTitle: 'Unit 4: Capitalization & Shift',
    title: '4.6 Natural Conversational Dialogue',
    description: 'Realistic dialogue mixing capitals, quotation marks, commas, and questions.',
    targetKeys: ['Shift', '"', ',', '.', '?'],
    targetAccuracy: 95,
    targetWpm: 32,
    content: '"Look here," said Marcus, "did you finish the report for Monday?" "Yes, entirely," replied Sarah.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 360,
  },

  // =========================================================================
  // UNIT 5: NUMBER ROW MASTERY (Upward Reaches 1-0)
  // =========================================================================
  {
    id: 'lesson-5-1',
    tier: 5,
    tierTitle: 'Unit 5: Number Row Mastery',
    title: '5.1 Left Hand Numbers: 1, 2, 3, 4, 5',
    description: 'Reach up from QWERT to the number row. Retain your home row orientation.',
    targetKeys: ['1', '2', '3', '4', '5'],
    targetAccuracy: 92,
    targetWpm: 22,
    content: '1 2 3 4 5 12 34 51 23 45 123 451 234 321 543 21 43 52 14',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 370,
  },
  {
    id: 'lesson-5-2',
    tier: 5,
    tierTitle: 'Unit 5: Number Row Mastery',
    title: '5.2 Right Hand Numbers: 6, 7, 8, 9, 0',
    description: 'Reach up from YUIOP to the number row with right hand fingers.',
    targetKeys: ['6', '7', '8', '9', '0'],
    targetAccuracy: 92,
    targetWpm: 22,
    content: '6 7 8 9 0 67 89 90 78 60 789 678 890 098 765 67 89 06',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 380,
  },
  {
    id: 'lesson-5-3',
    tier: 5,
    tierTitle: 'Unit 5: Number Row Mastery',
    title: '5.3 Mixed Digit Sequences & Codes',
    description: 'Ten-digit phone number, postal code, and identifier patterns.',
    targetKeys: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
    targetAccuracy: 93,
    targetWpm: 25,
    content: '800 555 0199 10452 90210 2026 404 8080 3000 1984 2001',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 390,
  },
  {
    id: 'lesson-5-4',
    tier: 5,
    tierTitle: 'Unit 5: Number Row Mastery',
    title: '5.4 Dates, Times & Formats',
    description: 'Years, clock times, and date formats mixing numbers with colons and hyphens.',
    targetKeys: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', '-'],
    targetAccuracy: 93,
    targetWpm: 25,
    content: '2026-09-19 12:45 08:30 2025-12-31 23:59 14:00 1999-01-01',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 400,
  },
  {
    id: 'lesson-5-5',
    tier: 5,
    tierTitle: 'Unit 5: Number Row Mastery',
    title: '5.5 Quantities & Measurements',
    description: 'Words paired directly with quantities (e.g. 50 miles, 12 items, 240 volts).',
    targetKeys: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'all'],
    targetAccuracy: 94,
    targetWpm: 28,
    content: 'flight 350 carried 180 passengers across 2400 miles in 4 hours',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 410,
  },
  {
    id: 'lesson-5-6',
    tier: 5,
    tierTitle: 'Unit 5: Number Row Mastery',
    title: '5.6 Tabular Data & Metrics',
    description: 'High-density statistics paragraphs mixing words, digits, and percentages.',
    targetKeys: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '%', 'all'],
    targetAccuracy: 94,
    targetWpm: 30,
    content: 'revenue grew 18% in 2025 with 450 new clients producing 980 orders',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 430,
  },

  // =========================================================================
  // UNIT 6: PUNCTUATION & CODE SYNTAX (Developer punctuation, braces, arrows)
  // =========================================================================
  {
    id: 'lesson-6-1',
    tier: 6,
    tierTitle: 'Unit 6: Punctuation & Code Syntax',
    title: '6.1 Mathematical & Currency Symbols',
    description: 'Shift-number symbols: $, %, &, *, +, =, -, and slashes.',
    targetKeys: ['$', '%', '&', '*', '+', '=', '-', '/'],
    targetAccuracy: 92,
    targetWpm: 24,
    content: '$50 + $25 = $75 and 100% of profit was $1200 with 15% discount',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 440,
  },
  {
    id: 'lesson-6-2',
    tier: 6,
    tierTitle: 'Unit 6: Punctuation & Code Syntax',
    title: '6.2 Brackets & Parentheses',
    description: 'Parentheses ( ), square brackets [ ], and array access syntax.',
    targetKeys: ['(', ')', '[', ']'],
    targetAccuracy: 93,
    targetWpm: 26,
    content: 'items[0] = list[i]; (a + b) * (c - d); values[count - 1];',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 450,
  },
  {
    id: 'lesson-6-3',
    tier: 6,
    tierTitle: 'Unit 6: Punctuation & Code Syntax',
    title: '6.3 Curly Braces & Scopes',
    description: 'Block delimiters { } and object literal syntax common in JavaScript, C, and Rust.',
    targetKeys: ['{', '}', ':', ';', ','],
    targetAccuracy: 93,
    targetWpm: 26,
    content: '{ id: 1, name: "user", score: 95 }; if (ok) { return true; }',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 460,
  },
  {
    id: 'lesson-6-4',
    tier: 6,
    tierTitle: 'Unit 6: Punctuation & Code Syntax',
    title: '6.4 Arrow Functions & Operators',
    description: 'Arrow tokens (=>), comparisons (<=, >=, ===), and logical operators (&&, ||).',
    targetKeys: ['=', '>', '<', '!', '&', '|'],
    targetAccuracy: 93,
    targetWpm: 28,
    content: 'const isReady = (x) => x >= 10 && x <= 100; valid = count !== 0;',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 480,
  },
  {
    id: 'lesson-6-5',
    tier: 6,
    tierTitle: 'Unit 6: Punctuation & Code Syntax',
    title: '6.5 Strings, Quotes & Literals',
    description: 'Single quotes, double quotes, backticks, and string template interpolation.',
    targetKeys: ["'", '"', '`', '$', '{', '}'],
    targetAccuracy: 93,
    targetWpm: 28,
    content: '`Welcome, ${user.name}! Your order "${item}" is ready.`',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 500,
  },
  {
    id: 'lesson-6-6',
    tier: 6,
    tierTitle: 'Unit 6: Punctuation & Code Syntax',
    title: '6.6 Full Developer Code Block',
    description: 'Realistic typed function body combining declarations, loops, and returns.',
    targetKeys: ['all'],
    targetAccuracy: 94,
    targetWpm: 32,
    content: 'async function fetchTotal(ids: number[]): Promise<number> { return ids.reduce((a, b) => a + b, 0); }',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 530,
  },

  // =========================================================================
  // UNIT 7: VELOCITY & CERTIFICATION SPRINTS (Endurance & Pace Benchmarks)
  // =========================================================================
  {
    id: 'lesson-7-1',
    tier: 7,
    tierTitle: 'Unit 7: Velocity & Certification',
    title: '7.1 Sustained 30 WPM Benchmark',
    description: 'Maintain steady rhythmic cadence across extended prose without pause.',
    targetKeys: ['all'],
    targetAccuracy: 95,
    targetWpm: 30,
    content: 'Consistency is the true foundation of high speed typing. When each stroke lands with equal tempo, endurance compounds effortlessly.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 550,
  },
  {
    id: 'lesson-7-2',
    tier: 7,
    tierTitle: 'Unit 7: Velocity & Certification',
    title: '7.2 Fluid 40 WPM Pace',
    description: 'Eliminate hesitation at word boundaries and build multi-character rolling reflexes.',
    targetKeys: ['all'],
    targetAccuracy: 95,
    targetWpm: 40,
    content: 'Focus on looking ahead by two or three words as you type. Your fingers should glide into place before the mind actively deliberates.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 600,
  },
  {
    id: 'lesson-7-3',
    tier: 7,
    tierTitle: 'Unit 7: Velocity & Certification',
    title: '7.3 Silver 50 WPM Velocity Sprint',
    description: 'Pass the 50 WPM professional velocity milestone with over 96% accuracy.',
    targetKeys: ['all'],
    targetAccuracy: 96,
    targetWpm: 50,
    content: 'Velocity is moving in the right direction without hesitation. Master every letter, stay relaxed, and let the rhythmic cadence carry your speed.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 700,
  },
  {
    id: 'lesson-7-4',
    tier: 7,
    tierTitle: 'Unit 7: Velocity & Certification',
    title: '7.4 Advanced 60 WPM Endurance',
    description: 'Longer paragraph with complex vocabulary, testing both speed and sustained stamina.',
    targetKeys: ['all'],
    targetAccuracy: 96,
    targetWpm: 60,
    content: 'Great typists maintain calm composure under speed pressure. Breathing steadily and releasing tension in the forearms keeps accuracy razor sharp across hundreds of consecutive words.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 850,
  },
  {
    id: 'lesson-7-5',
    tier: 7,
    tierTitle: 'Unit 7: Velocity & Certification',
    title: '7.5 Gold 70 WPM Master Sprint',
    description: 'The elite 70 WPM threshold — entering the top tier of competitive touch typing.',
    targetKeys: ['all'],
    targetAccuracy: 97,
    targetWpm: 70,
    content: 'Precision creates velocity. By trusting muscle memory completely and never looking down, you enter an effortless state of flow where thought turns into keystrokes instantly.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 1000,
  },
  {
    id: 'lesson-7-6',
    tier: 7,
    tierTitle: 'Unit 7: Velocity & Certification',
    title: '7.6 Grandmaster Capstone Test',
    description: 'Comprehensive test spanning literary prose, numbers, and punctuation at championship tempo.',
    targetKeys: ['all'],
    targetAccuracy: 98,
    targetWpm: 75,
    content: 'Mastery is not a final destination, but an unbroken habit of deliberate excellence. With every clean keystroke, you command your digital craft with complete authority.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 1500,
  },
];
