import { Lesson } from '@/types/typing';

export const LESSONS_CURRICULUM: Lesson[] = [
  // TIER 1: HOME ROW FOUNDATION
  {
    id: 'lesson-1-1',
    tier: 1,
    tierTitle: 'Tier 1: Home Row Foundation',
    title: '1.1 The Anchor Keys: F & J',
    description: 'Learn the tactile bumps on F and J. Your index fingers should always rest here.',
    targetKeys: ['f', 'j', ' '],
    targetAccuracy: 95,
    targetWpm: 18,
    content: 'fff jjj fff jjj fjf jfj ff jj f j fff jjj fff jjj fjf jfj',
    unlocked: true,
    completed: false,
    stars: 0,
    xpReward: 100,
  },
  {
    id: 'lesson-1-2',
    tier: 1,
    tierTitle: 'Tier 1: Home Row Foundation',
    title: '1.2 Left Hand Home: A S D F',
    description: 'Place your pinky on A, ring on S, middle on D, and index on F.',
    targetKeys: ['a', 's', 'd', 'f', ' '],
    targetAccuracy: 94,
    targetWpm: 20,
    content: 'asdf fdsa asdf fdsa asdf sad fad dad add sass dads fads lads',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 120,
  },
  {
    id: 'lesson-1-3',
    tier: 1,
    tierTitle: 'Tier 1: Home Row Foundation',
    title: '1.3 Right Hand Home: J K L ;',
    description: 'Place your index on J, middle on K, ring on L, and pinky on semicolon.',
    targetKeys: ['j', 'k', 'l', ';', ' '],
    targetAccuracy: 94,
    targetWpm: 20,
    content: 'jkl; ;lkj jkl; ;lkj all ask fall alas salad flasks fall fads',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 120,
  },
  {
    id: 'lesson-1-4',
    tier: 1,
    tierTitle: 'Tier 1: Home Row Foundation',
    title: '1.4 Reaching Inward: G & H',
    description: 'Stretch your left index to G and right index to H, then return to home.',
    targetKeys: ['g', 'h', 'a', 's', 'd', 'f', 'j', 'k', 'l'],
    targetAccuracy: 94,
    targetWpm: 22,
    content: 'fgf jhj fgf jhj glad half flag dash flash glass shag had gas gag',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 150,
  },

  // TIER 2: TOP & BOTTOM ROWS
  {
    id: 'lesson-2-1',
    tier: 2,
    tierTitle: 'Tier 2: Keyboard Reach',
    title: '2.1 Crucial Vowels: E & I',
    description: 'Left middle finger reaches up to E; right middle finger reaches up to I.',
    targetKeys: ['e', 'i', 'd', 'k'],
    targetAccuracy: 94,
    targetWpm: 24,
    content: 'ded kik ded kik feed seek file hide feel kid life like desk side fill',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 160,
  },
  {
    id: 'lesson-2-2',
    tier: 2,
    tierTitle: 'Tier 2: Keyboard Reach',
    title: '2.2 Index Reach: R & U',
    description: 'Left index reaches up to R; right index reaches up to U.',
    targetKeys: ['r', 'u', 'f', 'j'],
    targetAccuracy: 94,
    targetWpm: 25,
    content: 'frf juj frf juj fur jar run rush rule surf user true pure rug drug',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 180,
  },
  {
    id: 'lesson-2-3',
    tier: 2,
    tierTitle: 'Tier 2: Keyboard Reach',
    title: '2.3 Outer Top: Q, W, O, P',
    description: 'Left ring on W, pinky on Q. Right ring on O, pinky on P.',
    targetKeys: ['q', 'w', 'o', 'p'],
    targetAccuracy: 93,
    targetWpm: 25,
    content: 'sws lol aqa p;p slow pool prow quick power flow loop word pop drop',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 200,
  },
  {
    id: 'lesson-2-4',
    tier: 2,
    tierTitle: 'Tier 2: Keyboard Reach',
    title: '2.4 Bottom Row: Z, X, C, V, B, N, M',
    description: 'Carefully slide downward from home row without lifting whole hand.',
    targetKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm'],
    targetAccuracy: 93,
    targetWpm: 26,
    content: 'cave zinc back calm view zoom move bold next mask vine scan bomb',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 220,
  },

  // TIER 3: DIGRAPHS & NUMBERS
  {
    id: 'lesson-3-1',
    tier: 3,
    tierTitle: 'Tier 3: Flow & Digraphs',
    title: '3.1 Common Digraphs: th, he, in, er, an',
    description: 'Type these pairs as single fluid motions rather than individual letters.',
    targetKeys: ['t', 'h', 'e', 'i', 'n', 'r', 'a'],
    targetAccuracy: 95,
    targetWpm: 30,
    content: 'the there then their another thin father mother winter enter winner',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 240,
  },
  {
    id: 'lesson-3-2',
    tier: 3,
    tierTitle: 'Tier 3: Flow & Digraphs',
    title: '3.2 Shift & Capitalization',
    description: 'Use opposite hand Shift: right Shift for left hand letters, and vice versa.',
    targetKeys: ['Shift'],
    targetAccuracy: 94,
    targetWpm: 28,
    content: 'The quick Brown Fox jumps over the Lazy Dog with Great Speed and Joy',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 250,
  },
  {
    id: 'lesson-3-3',
    tier: 3,
    tierTitle: 'Tier 3: Flow & Digraphs',
    title: '3.3 Number Row: 1 2 3 4 5 6 7 8 9 0',
    description: 'Reach upward from the top row. Keep your wrists hovering slightly.',
    targetKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
    targetAccuracy: 92,
    targetWpm: 25,
    content: 'room 101 code 404 year 2026 count 789 flight 350 speed 100 level 42',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 280,
  },
  {
    id: 'lesson-3-4',
    tier: 3,
    tierTitle: 'Tier 3: Flow & Digraphs',
    title: '3.4 Punctuation Mastery',
    description: 'Commas, periods, question marks, and apostrophes without glancing down.',
    targetKeys: [',', '.', '?', '!', "'"],
    targetAccuracy: 94,
    targetWpm: 30,
    content: "Ready, set, go! Don't look at the keys; feel them. Is it working? Yes, indeed.",
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 300,
  },

  // TIER 4: DEVELOPER & SPEED MASTERY
  {
    id: 'lesson-4-1',
    tier: 4,
    tierTitle: 'Tier 4: Master & Code',
    title: '4.1 Developer Brackets & Operators',
    description: 'Brackets, braces, equals, and semicolons common in all programming languages.',
    targetKeys: ['{', '}', '(', ')', '[', ']', '=', ';', '<', '>'],
    targetAccuracy: 93,
    targetWpm: 26,
    content: 'if (x >= 10) { return items[0]; } const fn = () => { let val = 42; };',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 350,
  },
  {
    id: 'lesson-4-2',
    tier: 4,
    tierTitle: 'Tier 4: Master & Code',
    title: '4.2 Rhythmic Prose & Flow',
    description: 'Maintain smooth cadence across full sentence structures and transitions.',
    targetKeys: ['all'],
    targetAccuracy: 96,
    targetWpm: 40,
    content: 'Rhythm is the secret to high speed typing. When your keystrokes land with equal spacing, mistakes vanish and endurance soars effortlessly.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 400,
  },
  {
    id: 'lesson-4-3',
    tier: 4,
    tierTitle: 'Tier 4: Master & Code',
    title: '4.3 The 50 WPM Velocity Sprint',
    description: 'Pass the 50 Words Per Minute threshold with over 95% accuracy to earn the Velocity badge.',
    targetKeys: ['all'],
    targetAccuracy: 95,
    targetWpm: 50,
    content: 'Velocity is not simply moving fast; it is moving in the right direction without hesitation. Master each letter, maintain calm composure, and let every word flow seamlessly.',
    unlocked: false,
    completed: false,
    stars: 0,
    xpReward: 500,
  }
];
