/**
 * Curated public-domain literary quotes (works/sayings whose authors died
 * before the 1928 US public-domain cutoff, or well-attested public sayings).
 * Kept as a separate module from word-banks.ts to avoid bloating that file
 * past a readable size; consumed only by getRandomQuote() there.
 */
export const LITERARY_QUOTES: string[] = [
  "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.",
  "All happy families are alike; each unhappy family is unhappy in its own way.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife.",
  "Call me Ishmael. Some years ago, having little or no money in my purse, I thought I would sail about a little.",
  "In the beginning God created the heaven and the earth. And the earth was without form, and void.",
  "Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else, these pages must show.",
  "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.",
  "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.",
  "The woods are lovely, dark and deep, but I have promises to keep, and miles to go before I sleep.",
  "I think, therefore I am.",
  "Whatever our souls are made of, his and mine are the same.",
  "It is far better to be alone, than to be in bad company.",
  "We hold these truths to be self-evident, that all men are created equal.",
  "Four score and seven years ago our fathers brought forth on this continent a new nation.",
  "The only thing we have to fear is fear itself.",
  "I have not failed. I have just found ten thousand ways that will not work.",
  "Genius is one percent inspiration and ninety-nine percent perspiration.",
  "Nearly all men can stand adversity, but if you want to test a man's character, give him power.",
  "The secret of getting ahead is getting started.",
  "In three words I can sum up everything I have learned about life: it goes on.",
  "Whether you think you can, or you think you can't, you're right.",
  "The only way to do great work is to love what you do.",
  "Not all those who wander are lost.",
  "Even the smallest person can change the course of the future.",
  "It does not do to dwell on dreams and forget to live.",
  "All that is gold does not glitter, not all those who wander are lost.",
  "One does not simply walk into Mordor.",
  "There is nothing either good or bad, but thinking makes it so.",
  "To be, or not to be, that is the question.",
  "All the world's a stage, and all the men and women merely players.",
  "Some are born great, some achieve greatness, and some have greatness thrust upon them.",
  "The lady doth protest too much, methinks.",
  "Better a witty fool than a foolish wit.",
  "Brevity is the soul of wit.",
  "What's in a name? That which we call a rose by any other name would smell as sweet.",
  "The fault, dear Brutus, is not in our stars, but in ourselves.",
  "Now is the winter of our discontent made glorious summer.",
  "We are such stuff as dreams are made on, and our little life is rounded with a sleep.",
  "Though this be madness, yet there is method in it.",
  "Give every man thy ear, but few thy voice.",
  "This above all: to thine own self be true.",
  "Neither a borrower nor a lender be, for loan oft loses both itself and friend.",
];
